# Generated by Django 5.2.11 on 2026-03-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('annual_income', models.FloatField()),
                ('spending_score', models.FloatField()),
                ('cluster', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
